language: java
install: true

jdk:
- oraclejdk8

script:
- ./gradlew sonarqube

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

addons:
  sonarcloud:
    organization: scndry-github
    token:
      secure: JooYwe1f2XYH3611b0AAhnXMnQwA17jUOx/gUwSS2FSVgXIkA6PjwEGCakrVmBluHfD8vl3izjXJsgjxwnMHa91BNDRpD5vVTEpQNl6n7jRy88x981YXYjS8F3sl8CxX7FGJJ/wHfk5C3fbIKV4yF3+ck3qNBYfDHINDUsYdKjTCay6MJ5jMkDqCNSbSFWmCCIIS3S+IXlvH7LGZHFuXBbbmOsYNQJck7pDgLslsKkQzVbZo86TRPP9K/WE5hNsYwU/6e0FncilzehOUcRfpOmcLiKSz6VLDA2Mdro0RUF4P1ZQtfQV6nFEXnBB6pT/IV2bf7FkNbrk1Xws8s2riytM0tQUyUaGe888dKOxrwSOU76ftTYqfCjuUIwqFwUyAyQZGWahdqV3v84k8uYYaAIUIx727lr2D31Oq4VK73oQ06eueAozt14eEw5B0sTde1zQAxi9Bvi1aZD0nxC6HJbnOG2ECkRNq3PhWIco9MTiPeR4+jgxvUwDwtXjIQV2TKhAnu3OQ+TJfo04eM8U76qczDaipBY/Iajy2Ts0ZPBOuA2lDvMswYFelhqiWVq7IK5iSSDheQABKTeAYNC8UqHnR9vDpzSO+nz2nuW1F0SFclOU4Y9u3mBRQUiU/2/DoBZQtjELbRTY4C1a4dDgWTgJPaUEdGKOwHLxOsFWwnIM=
